#ifndef MICROPY_INCLUDED_WASM_COMMON_HAL_MICROCONTROLLER_PROCESSOR_H
#define MICROPY_INCLUDED_WASM_COMMON_HAL_MICROCONTROLLER_PROCESSOR_H

#define COMMON_HAL_MCU_PROCESSOR_UID_LENGTH 12

#include "py/obj.h"

typedef struct
{
    mp_obj_base_t base;
} mcu_processor_obj_t;

#endif  // MICROPY_INCLUDED_WASM_COMMON_HAL_MICROCONTROLLER_PROCESSOR_H
